name: Check Files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CLI
      run: time cargo install collective --locked --quiet && collective --version
    - name: Validate Requests
      run: collective check join-request
    - name: Validate Evidence
      run: collective check evidence
